name: clubimperial
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  dio: ^3.0.9
  get: ^3.5.4
  get_storage: ^1.3.0
  google_fonts: ^1.1.0
  flutter_form_bloc: ^0.13.0
  qr_flutter: ^3.1.0
  badges: ^1.1.1
  
  carousel_slider: ^1.4.1
  image_picker: ^0.6.3+1
  connectivity: ^0.4.6
  
  # Estas librerias son las que se agregaron despues
  cached_network_image: ^2.1.0
  shimmer: ^1.1.1
  shared_preferences: ^0.5.6
  http: ^0.12.0

  
  flutter_swiper: ^1.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/login.jpg
    - assets/images/banner-home.png
    - assets/images/gallery/galeria-1.png
    - assets/images/gallery/galeria-2.png
    - assets/images/gallery/galeria-3.png
    - assets/images/gallery/galeria-4.png
    - assets/images/gallery/galeria-5.png
    - assets/images/gallery/galeria-6.png
    - assets/images/gallery/galeria-7.png
    - assets/images/gallery/galeria-8.png
    - assets/images/cardwallet/visa_logo.png
    - assets/images/cardwallet/creditcardchipsilver.png
    - assets/images/cardwallet/card_band.jpg
    - assets/images/cardwallet/card_back.jpg
    - assets/images/card_provider/american_express.png
    - assets/images/card_provider/diners_club.png
    - assets/images/card_provider/jcb.png
    - assets/images/card_provider/master_card.png
    - assets/images/card_provider/maestro.png
    - assets/images/card_provider/rupay.png
    - assets/images/card_provider/visa.png
    - assets/images/card_provider/contactless_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Bold.ttf
          weight: 900
        - asset: fonts/BebasNeue-Book.ttf
        - asset: fonts/BebasNeue-Light.ttf
          weight: 300
        - asset: fonts/BebasNeue-Regular.ttf
          weight: 400
        - asset: fonts/BebasNeue-Thin.ttf
          weight: 200
          style: italic
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-Hairline.ttf
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Regular.ttf
          weight: 400
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oswald/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Oswald/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
          weight: 400
    - family: Open Sans Condensed
      fonts:
        - asset: assets/fonts/Open_Sans_Condensed/OpenSansCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans_Condensed/OpenSansCondensed-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
